-- Documentation only: do not run this file as a migration.
--
-- The Supabase project already contains the following tables. This repository
-- must not create, alter, or migrate them. It also must never access the
-- unrelated public.leads table.
--
-- Existing public.lgs_leads contract:
--   id                bigserial primary key
--   business_name     text
--   address           text
--   phone             text
--   website           text
--   business_type     text
--   google_place_id   text unique
--   status            text default 'new', constrained to exactly:
--                     new | verified | moved | opted_out | drafted
--   opted_out         boolean default false
--   last_seen_at      timestamp
--   created_at        timestamp default now()
--   updated_at        timestamp default now()
--
-- Existing public.lgs_outreach_tracker contract:
--   id                bigserial primary key
--   lead_id           bigint references lgs_leads(id) on delete cascade
--   email_draft       text
--   email_sent        boolean default false
--   sent_at           timestamp
--   response_received boolean default false
--   response_text     text
--   response_date     timestamp
--   notes             text
--   created_at        timestamp default now()
--   updated_at        timestamp default now()
--
-- No executable SQL statements are intentionally included.
